### ISSUE TITLE
Ped not showing no shoes, 

### ISSUE THREAD

**Issue by MichyMedia** [YeahItsHayden/shoestealing#1]
when you steal the persons shoes, the animation happens and then the person that does the command can see the shoes removed but not the other players

**Comment by TheCorruptCode** [comment]
I'll look into it

**Comment by TheCorruptCode** [comment]
Fixed. Download latest

**Comment by MichyMedia** [comment]
thanks this is now working, do you have discord?? would love to talk to you more about some stuff. 

Also would it be possible to add a text above head, i have the sript that does it just need to to "/do TAKE SHOES"

**Comment by MichyMedia** [comment]
also only lets you steal one persons shoes. is it a timed thing. restart the script and its fine
